show databases;
use join_practice;
show tables;

CREATE TABLE departments (
 dept_id INTEGER PRIMARY KEY,
 dept_name TEXT
);
CREATE TABLE doctors (
 doc_id INTEGER PRIMARY KEY,
 doc_name TEXT,
 dept_id INTEGER,
 mentor_id INTEGER
);
CREATE TABLE patients (
 patient_id INTEGER PRIMARY KEY,
 patient_name TEXT,
 city TEXT
);
CREATE TABLE appointments (
 appt_id INTEGER PRIMARY KEY,
 doc_id INTEGER,
 patient_id INTEGER,
 appt_date DATE,
 fee DECIMAL(10,2)
);

show tables;
INSERT INTO departments VALUES
(1, 'Cardiology'),
(2, 'Neurology'),
(3, 'Orthopedics');
select * from departments ;

INSERT INTO doctors VALUES
(1, 'Dr. Smith', 1, NULL),
(2, 'Dr. Jones', 1, 1),
(3, 'Dr. House', 2, 1),
(4, 'Dr. Chase', NULL, 3),
(5, 'Dr. Foreman', 2, 3);
select * from doctors;

INSERT INTO patients VALUES
(1, 'Alice', 'New York'),
(2, 'Bob', 'Chicago'),
(3, 'Charlie', 'New York'),
(4, 'Diana', 'Boston'),
(5, 'Eve', 'Chicago');
select * from patients;

INSERT INTO appointments VALUES
(1, 1, 1, '2026-10-01', 150.00),
(2, 2, 2, '2026-10-02', 200.00),
(3, 1, 3, '2026-10-03', 150.00),
(4, 3, 1, '2026-10-04', 300.00),
(5, NULL, 4, '2026-10-05', 100.00),
(6, 4, NULL, '2026-10-06', 250.00),
(7, 5, 2, '2026-10-07', 200.00);
select * from appointments;	
use join_practice;

# Section 1: INNER JOINS (1-10) :

#(INNER JOIN)  
#1)List doctors and their department names.
select dr.doc_name , d.dept_name 
from doctors dr inner join departments d on d.dept_id = dr.dept_id ;

#2.)List appointments with their assigned doctor names
select a.appt_id , d.doc_name 
from appointments a inner join doctors d on a.doc_id = d.doc_id ;

#3.) List appointments with their patient names.
select a.appt_id , p.patient_name
from appointments a inner join patients p on  a.patient_id = p.patient_id ;

#4.) List doctor names, patient names, and fees for all valid appointments.
select d.doc_name , p.patient_name , a.fee
from doctors d inner join appointments a on a.doc_id = d.doc_id 
inner join patients p on a.patient_id = p.patient_id ;

#5.) Find doctors specifically in the 'Cardiology' department.
select d.doc_name from doctors d inner join departments a on d.dept_id = a.dept_id where a.dept_name = 'Cardiology';

#6.) Find the total fees collected by each doctor.
select d.doc_name , sum(a.fee) as total_fee 
from doctors d inner join appointments a on a.doc_id = d.doc_id 
group by d.doc_name ;

#7.) Count the total number of appointments per patient.
select p.patient_name , count(a.appt_id) as total_appointments 
from patients p inner join appointments a on a.patient_id = p.patient_id 
group by p.patient_name ;

#8.) Find patients who have spent more than 200 in total fees.
select p.patient_name , sum(a.fee) as total_fee 
from patients p inner join appointments a on a.patient_id = p.patient_id 
group by p.patient_name 
having total_fee > 200  ;

#9) Find doctors who have conducted more than 1 appointment.
select d.doc_name , count(a.doc_id) as total_appointment 
from doctors d inner join appointments a on d.doc_id = a.doc_id 
group by d.doc_name 
having total_appointment > 1 ;

#10) ) List department names and the total fees generated by their doctors.
select d.dept_name , sum(a.fee) as total_revenue 
from departments d inner join doctors dr on d.dept_id = dr.dept_id 
inner join appointments a on a.doc_id = dr.doc_id 
group by d.dept_name ;


# LEFT JOIN :

#11)  List all doctors and their departments, including doctors with no department.
select dr.doc_name , d.dept_name 
from doctors dr left join departments d on d.dept_id = dr.dept_id ;

#12)  List all departments and their doctors, including departments with no doctors.
select d.dept_name  , dr.doc_name 
from  departments d left join doctors dr on d.dept_id = dr.dept_id ;

#13) List all patients and their appointment dates, including patients who never booked
select p.patient_name , a.appt_date 
from patients p left join appointments a on a.patient_id = p.patient_id ;

#14) List all appointments and their assigned doctors, including unassigned appointments
select a.appt_id , d.doc_name 
from appointments a left join doctors d on d.doc_id = a.doc_id ;

#15) Find doctors who have exactly zero appointments.
select d.doc_name , count(a.appt_id)  
from doctors d left join appointments a on d.doc_id = a.doc_id 
group by d.doc_name 
having count(a.appt_id) = 0 ;

#16) Find patients who have never booked an appointment.
select p.patient_name , count(a.appt_id)
from patients p left join appointments a on a.patient_id = p.patient_id 
group by p.patient_name 
having count(a.appt_id)= 0 ;

#17) Find departments that have no assigned doctor
select d.dept_name , count(dr.doc_id) 
from departments d left join doctors dr on dr.dept_id = d.dept_id
group by d.dept_name 
having count(dr.doc_id) = 0;

#To Ask :
#18)  Calculate total fees per patient, replacing NULLs with 0 for patients with no appointments
select p.patient_name , sum(a.fee) as total_spend 
from patients p left join appointments a on a.patient_id = p.patient_id 
group by p.patient_name;

#19)Count total appointments per doctor, ensuring doctors with 0 show up
SELECT d.doc_name, COUNT(a.appt_id) AS total_appointments
FROM doctors d LEFT JOIN appointments a ON d.doc_id = a.doc_id
GROUP BY  d.doc_name;

#20) List all doctors, their department names, and their total number of appointments
select dr.doc_name , d.dept_name , COALESCE(count(a.appt_id), 0) as total_appt 
from doctors dr left join departments d on d.dept_id = dr.dept_id 
left join appointments a on a.doc_id =  dr.doc_id 
group by dr.doc_name , d.dept_name ;

use join_practice;
# RIGHT JOIN ;
#21) List all departments and their doctors. (Simulated using LEFT JOIN for SQLite execution.
select  d.dept_name  , dr.doc_name 
from doctors dr right join departments d on  d.dept_id = dr.dept_id;

#22) List all patients and their appointments. (Simulated via LEFT JOIN).
select p.patient_name , a.appt_date 
from appointments a right join patients p on p.patient_id = a.patient_id ;

#23)  List all doctors and their appointments, ensuring all doctors are included:
select d.doc_name , a.appt_date 
from appointments a right join doctors d on d.doc_id = a.doc_id; 

#24) Find departments with no doctors using a Right Join pattern
select d.dept_name 
from doctors dr right join departments d on d.dept_id = dr.dept_id
where dr.doc_id is Null ;

#25)  Find patients with no appointments using a Right Join pattern
select p.patient_name 
from appointments a right join patients p on a.patient_id = p.patient_id 
where a.appt_id is null ;

#26) Find the total number of appointments per department, ensuring all departments show
select d.dept_name , count(a.appt_id) as total_appt 
from appointments a right join doctors dr  on a.doc_id = dr.doc_id 
right join departments d on d.dept_id = dr.dept_id 
group by d.dept_name ;

#27) Find doctors with 0 appointments using a Right Join pattern.
select d.doc_name 
from appointments a right join doctors d on a.doc_id = d.doc_id 
where a.appt_id is null ;

#28) List all appointments and patients, ensuring all patients are included\
select a.appt_id , p.patient_name 
from appointments a right join patients p on a.patient_id = p.patient_id ;

#29) List all appointments and doctors, ensuring all doctors are included.
select a.appt_id , d.doc_name 
from appointments a right join doctors d on a.doc_id = d.doc_id ;

#30) Calculate average fee per patient, ensuring all patients show
select p.patient_name , avg(a.fee) as avg_fee 
from appointments a right join patients p on a.patient_id = p.patient_id 
group by p.patient_name ;

 # CROSS & FULL OUTER JOINS:
 use join_practice;

#31)  List all possible combinations of doctors and patients.
select d.doc_name , p.patient_name 
from  patients p join doctors d ; 

#32) Count the total number of possible doctor-patient pairings. 
select count(*) as total_combinaion 
from patients p cross  join doctors d ;

#33) List all combinations of doctors and departments
select dr.doc_name , d.dept_name 
from departments d cross join doctors dr ;

#34) List all doctors and departments, matching where possible, and including unmatched records from both sides.
select dr.doc_name , d.dept_name 
from  doctors dr left join  departments d  on d.dept_id = dr.dept_id 
union
select dr.doc_name , d.dept_name 
from  doctors dr right  join  departments d  on d.dept_id = dr.dept_id ;

#35) List all patients and appointments, matching where possible, including orphans from both.
select p.patient_name , a.appt_id 
from   patients p  left join appointments a  on p.patient_id = a.patient_id 
union 
select p.patient_name , a.appt_id 
from   patients p  right join appointments a  on p.patient_id = a.patient_id ;

#36) ) Find orphaned doctors or orphaned departments (those without matches).
select dr.doc_name , d.dept_name 
from  doctors dr left join  departments d  on d.dept_id = dr.dept_id 
where d.dept_name is null 
union 
select dr.doc_name , d.dept_name 
from  departments d left join  doctors dr on d.dept_id = dr.dept_id 
where dr.doc_name is null ;

#37)  Find orphaned patients or orphaned appointments
select p.patient_name , a.appt_id 
from   patients p  left join appointments a  on p.patient_id = a.patient_id 
where a.appt_id is null 
union 
select p.patient_name , a.appt_id 
from   appointments a left join patients p   on p.patient_id = a.patient_id 
where p.patient_name is null ;

# SELF JOINS & COMPLEX QUERIES:

#38) ) List doctors alongside the names of their mentors.
select d1.doc_name as doctor_name , d2.doc_name as doc_mentor 
from doctors d1 join doctors d2 on d1.mentor_id = d2.doc_id ;

#39) List ALL doctors and their mentors, including doctors who have no mentor
SELECT d1.doc_name AS doctor_name,
       d2.doc_name AS doc_mentor
FROM doctors d1
LEFT JOIN doctors d2
ON d1.mentor_id = d2.doc_id;

#40) Count how many mentees each mentor has.
SELECT d.doc_name AS mentor,
       COUNT(m.doc_id) AS mentee_count
FROM doctors d
JOIN doctors m
ON m.mentor_id = d.doc_id
GROUP BY d.doc_id, d.doc_name;

























